version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: local-mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=231304
    volumes:
      - local-mysql-data:/var/lib/mysql

volumes:
  local-mysql-data:
