// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package pg_db

import (
	"context"
	"database/sql"
)

const createShortURL = `-- name: CreateShortURL :execresult
INSERT INTO url_shortener (
  id, original_url, shortkey
) VALUES (
 ?, ?, ?
)
`

type CreateShortURLParams struct {
	ID          string
	OriginalUrl string
	Shortkey    string
}

func (q *Queries) CreateShortURL(ctx context.Context, arg CreateShortURLParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createShortURL, arg.ID, arg.OriginalUrl, arg.Shortkey)
}

const getURL = `-- name: GetURL :one
SELECT id, original_url, shortkey, hit_count, created_at FROM url_shortener
WHERE original_url = ?
`

func (q *Queries) GetURL(ctx context.Context, originalUrl string) (UrlShortener, error) {
	row := q.db.QueryRowContext(ctx, getURL, originalUrl)
	var i UrlShortener
	err := row.Scan(
		&i.ID,
		&i.OriginalUrl,
		&i.Shortkey,
		&i.HitCount,
		&i.CreatedAt,
	)
	return i, err
}
